client_details = {
            "Title": 'Mr',
            "Firstname": 'Gerald',
            "Lastname": 'Smith',
            "Pronouns": 'he/him',
            "Date_of_Birth": '15/12/1990',
            "Occupation": 'Software Engineer',
            "Account_Balance": 100,
            "Overdraft_Limit": 10
        }
acc_neg_bal_exp = [{'Account_Balance': -967059627,
  'Date_of_Birth': '10/09/1997',
  'Firstname': 'Yule',
  'Lastname': 'Dach',
  'Occupation': 'Structural Engineer',
  'Overdraft_Limit': 884731888,
  'Pronouns': 'he/him',
  'Title': 'Rev'}, {'Account_Balance': -633176238,
  'Date_of_Birth': '08/01/1997',
  'Firstname': 'Catlee',
  'Lastname': 'Ayshford',
  'Occupation': 'Research Associate',
  'Overdraft_Limit': 534806598,
  'Pronouns': 'she/her',
  'Title': 'Mrs'},{'Account_Balance': -72798015,
  'Date_of_Birth': '7/01/1955',
  'Firstname': 'Loy',
  'Lastname': 'Brewis',
  'Occupation': 'Environmental Specialist',
  'Overdraft_Limit': 939400254,
  'Pronouns': 'he/him',
  'Title': 'Mrs'},{'Account_Balance': -880727976,
  'Date_of_Birth': '10/06/1963',
  'Firstname': 'Tripp',
  'Lastname': 'Delamere',
  'Occupation': 'Occupational Therapist',
  'Overdraft_Limit': 24833986,
  'Pronouns': 'he/him',
  'Title': 'Dr'}]
acc_searching_by_firstname = [{'Account_Balance': 58438860,
  'Date_of_Birth': '4/04/2000',
  'Firstname': 'Wilma',
  'Lastname': 'Huniwall',
  'Occupation': 'Human Resources Assistant II',
  'Overdraft_Limit': 3867051,
  'Pronouns': 'they/them',
  'Title': 'Rev'},{'Account_Balance': 58438860,
  'Date_of_Birth': '4/04/2000',
  'Firstname': 'Wilma',
  'Lastname': 'Huny',
  'Occupation': 'Assistant II',
  'Overdraft_Limit': 3867,
  'Pronouns': 'they/them',
  'Title': 'Rev'}]
acc_searching_by_lastname = [{'Account_Balance': 58438860,
  'Date_of_Birth': '4/04/2000',
  'Firstname': 'Wilma',
  'Lastname': 'Huniwall',
  'Occupation': 'Human Resources Assistant II',
  'Overdraft_Limit': 3867051,
  'Pronouns': 'they/them',
  'Title': 'Rev'}]
acc_searching_by_date_of_birth = [{'Account_Balance': 414546988,
  'Date_of_Birth': '10/04/1979',
  'Firstname': 'Delphine',
  'Lastname': 'Neiland',
  'Occupation': 'VP Marketing',
  'Overdraft_Limit': 55133275,
  'Pronouns': 'she/her',
  'Title': 'Mrs'}]
client = {
        "Title": 'Mr',
        "Firstname": "Henry",
        "Lastname": 'Smith',
        "Pronouns": 'he/him',
        "Date_of_Birth": '15/12/1990',
        "Occupation": 'Software Engineer',
        "Account_Balance": 100,
        "Overdraft_Limit": 10
    }
client1 = {
        "Title": 'Mr',
        "Firstname": "Sana",
        "Lastname": 'Sith',
        "Pronouns": 'she/her',
        "Date_of_Birth": '15/11/1990',
        "Occupation": 'Engineer',
        "Account_Balance": 100,
        "Overdraft_Limit": 10
    }
client2 = {
        "Title": 'Mrs',
        "Firstname": "Harriet",
        "Lastname": 'Dott',
        "Pronouns": 'she/her',
        "Date_of_Birth": '15/12/2000',
        "Occupation": 'Bartender',
        "Account_Balance": 1000,
        "Overdraft_Limit": 100
    }
client3 = {
        "Title": 'Mr',
        "Firstname": "Harry",
        "Lastname": 'James',
        "Pronouns": 'he/him',
        "Date_of_Birth": '5/12/1990',
        "Occupation": 'Librarian',
        "Account_Balance": 200,
        "Overdraft_Limit": 185
    }
client4 = {
            "Title": 'Mrs',
            "Firstname": 'Ayesha',
            "Lastname": 'Jannet',
            "Pronouns": 'she/her',
            "Date_of_Birth": '17/05/1990',
            "Occupation": 'Student',
            "Account_Balance": 468,
            "Overdraft_Limit": 101
}
